name: docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - run: pip install -r docs/requirements.txt
      - run: sudo apt-get update && sudo apt-get install -y pandoc

      - run: sphinx-build -b html docs/source site

      # upload *once*
      - uses: actions/upload-pages-artifact@v3
        with: { path: site }

      - uses: actions/deploy-pages@v4
